"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Base dir absolute path relative to the settings.py file
# TEMPLATES, DATABASES and STATICFILES directives use this BASE_DIR to refernce thier actual directories
# here the BASE_DIR = backend
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's8e4)(@2uihnctsrz2mhct*fdah%^vs!7&-l6((h1u8=5abo@h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# allow any host server to reach app from its IP
ALLOWED_HOSTS = ['*']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition
# it lists the apps that python interpriter fetches one by one in a row
# To allow python to render your app templates while interpriting code
INSTALLED_APPS = [
    'accounts',         # accounts templates will be rendered first at server startup
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # my apps
    'job',
    'bootstrap4',
    'django_filters',
    'contact',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "..", "frontend", "templates"),  # Adjusted path for templates BASE_DIR/../frontend/templates
        ],
        'APP_DIRS': True,       # This setting tells Django to look for templates in each app 'templates' directory, like backend/job/templates. /accounts/templates. 
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),   # backend/db.sqlite3
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# refers to the static files folder name, not the path
STATIC_URL = '/static/'

# actual path of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "..", "frontend", "static"),  # Adjusted path for static files  backend/../frontend/static
    # '/var/www/static/',
]

# name and path of website media files like the profile photo, jobs images, etc..
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "../..", "media")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'pythondeveloper6@gmail.com'
EMAIL_HOST_PASSWORD = 'kcpnwirvkmagqrlr'
EMAIL_USE_TLS = True
EMAIL_PORT = '587'