name: ci pipeline for django-job-board application

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: welcome message
      run: echo "starter workflow"
    - name: list files
      run: ls
    - name: read readme file
      run: cat StudyNotes.md
      