---
- name: Container and image create and clean
  hosts: localhost
  tasks:
  - name: delete stopped/running container
    command: sudo podman rm -f django-job-board
    ignore_errors: yes

  - name: delete unused image
    command: sudo podman rmi django-img
    ignore_errors: yes

  - name: Build new django-img
    command: sudo podman build -t django-img .


  - name: Run new django-job-board container
    command: sudo podman run -d --name django-job-board -p 8080:8000 django-img
