name: ci pipeline for django-job-board application

on:
  workflow_dispatch: 
  push:  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4 
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        cd Projects/django-job-board
        make setup
        make install


        
# jobs:
#     unit-testing:
#         name: Unit Testing
#         runs-on: ubuntu-latest
#         steps:
#         - name: Checkout Repository
#           uses: actions/checkout@v4

#         - name: Setup NodeJS Version
#           uses: actions/setup-node@v4
#           with:
#             node-version: 20
    
#         - name: Install Dependencies
#           run: npm install
    
#         - name: Unit Testing
#           run: npm test
          
#         - name: Archive Test Result
#           uses: actions/upload-artifact@v4
#           with:
#             name: Mocha-Test-Result
#             path: test-results.xml
            